// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GestionarConsultaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gestionarConsulta() {
    driver.get("https://localhost:8443/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector("#medico > span")).click();
    driver.findElement(By.id("usuario")).click();
    driver.findElement(By.id("usuario")).sendKeys("5555A");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.id("Confirmar")).click();
    driver.findElement(By.id("usuario")).click();
    driver.findElement(By.id("usuario")).sendKeys("22222222B");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("pas");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("usuario")).click();
    driver.findElement(By.id("usuario")).sendKeys("22222222B");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.id("Confirmar")).click();
    driver.findElement(By.cssSelector("#siguiente > span")).click();
    driver.findElement(By.id("suspender_consulta")).click();
    driver.findElement(By.cssSelector("#siguiente > span")).click();
    driver.findElement(By.id("historial")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("receta")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("pruebas")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("gestion_citas")).click();
    driver.findElement(By.id("nombrePaciente")).click();
    driver.findElement(By.id("nombrePaciente")).sendKeys("Raul ");
    driver.findElement(By.id("fechaCita")).click();
    driver.findElement(By.id("fechaCita")).sendKeys("0002-05-10");
    driver.findElement(By.id("fechaCita")).sendKeys("0020-05-10");
    driver.findElement(By.id("fechaCita")).sendKeys("0202-05-10");
    driver.findElement(By.id("fechaCita")).sendKeys("2023-05-10");
    driver.findElement(By.id("horaCita")).click();
    driver.findElement(By.id("horaCita")).sendKeys("10:03");
    driver.findElement(By.id("motivoCita")).click();
    driver.findElement(By.id("motivoCita")).sendKeys("esta malo");
    driver.findElement(By.cssSelector("input:nth-child(9)")).click();
    driver.findElement(By.id("finalizar")).click();
    driver.findElement(By.cssSelector(".logout")).click();
  }
}
